apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: must-gather-shared
  namespace: must-gather
  labels:
    app: must-gather
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
