---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rca-ephemeral-ns-manager
  namespace: ephemeral-ns
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["gcp-credentials", "intelliaide-system-app-config"]
    verbs: ["get", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rca-api-remote-binding
  namespace: ephemeral-ns
subjects:
  - kind: ServiceAccount
    name: rca-api-remote
    namespace: ephemeral-ns
roleRef:
  kind: Role
  name: rca-ephemeral-ns-manager
  apiGroup: rbac.authorization.k8s.io
