---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rca-api-remote
  namespace: ephemeral-ns
  labels:
    app: intelliaide-api
    purpose: cross-cluster-job-management

# Use the token from this Secret to populate the kubeconfig in
# k8s/control-cluster/remote-kubeconfig-secret.template.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: rca-api-remote-token
  namespace: ephemeral-ns
  annotations:
    kubernetes.io/service-account.name: rca-api-remote
type: kubernetes.io/service-account-token
