---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: api-local-storage
  namespace: must-gather
  labels:
    app: must-gather-api
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
